--PRIMARY KEY--

ALTER TABLE HORARIO ADD CONSTRAINT PK_HORARIO PRIMARY KEY (ID_HORARIO);
ALTER TABLE EVENTO ADD CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO);
ALTER TABLE SESION ADD CONSTRAINT PK_SESION PRIMARY KEY (ID_SESION);
ALTER TABLE SALAS ADD CONSTRAINT PK_SALA PRIMARY KEY (ID_SALA);
ALTER TABLE BITACORADEASISTENCIA ADD CONSTRAINT PK_BITACORA PRIMARY KEY (ID_BITACORA);
ALTER TABLE REFRIGERIO ADD CONSTRAINT PK_REFRIGERIO PRIMARY KEY (ID_REFRIGERIO);
ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (ID_MENU);
ALTER TABLE MESAREDONDA ADD CONSTRAINT PK_MESAREDONDA PRIMARY KEY (ID_MESAREDONDA);
ALTER TABLE INGREDIENTE ADD CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID_INGREDIENTE);
ALTER TABLE MODERADOR ADD CONSTRAINT PK_MODERADOR PRIMARY KEY (ID_MODERADOR);
ALTER TABLE EXPOSICION ADD CONSTRAINT PK_EXPOSICION PRIMARY KEY (ID_EXPOSICION);
ALTER TABLE EXPOSITOR ADD CONSTRAINT PK_EXPOSITOR PRIMARY KEY (ID_EXPOSITOR);
ALTER TABLE TEMA ADD CONSTRAINT PK_TEMA PRIMARY KEY (ID_TEMA);
ALTER TABLE PERSONA ADD CONSTRAINT PK_PERSONA PRIMARY KEY (ID_PERSONA);
ALTER TABLE CIUDAD ADD CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD);
ALTER TABLE PAIS ADD CONSTRAINT PK_PAIS PRIMARY KEY (ID_PAIS);
ALTER TABLE CONTINENTE ADD CONSTRAINT PK_CONTINENTE PRIMARY KEY (ID_CONTINENTE);
ALTER TABLE VISITANTES ADD CONSTRAINT PK_VISITANTE PRIMARY KEY (ID_VISITANTE);
ALTER TABLE TIPOUSUARIO ADD CONSTRAINT PK_TIPOUSUARIO PRIMARY KEY (IDTIPOUSUARIO);

--FOREIGN KEY--

ALTER TABLE EVENTO ADD CONSTRAINT FK_ID_HORARIO FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO (ID_HORARIO);
ALTER TABLE EVENTO ADD CONSTRAINT FK_ID_SALA FOREIGN KEY (ID_SALA) REFERENCES SALAS (ID_SALA);
ALTER TABLE SALAS ADD CONSTRAINT FK_ID_SESION FOREIGN KEY (ID_SESION) REFERENCES SESION (ID_SESION);
ALTER TABLE MENU ADD CONSTRAINT FK_ID_INGREDIENTE FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE (ID_INGREDIENTE);
ALTER TABLE REFRIGERIO ADD CONSTRAINT FK_ID_MENU FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU);
ALTER TABLE BITACORADEASISTENCIA ADD CONSTRAINT FK_ID_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA);
ALTER TABLE BITACORADEASISTENCIA ADD CONSTRAINT FK_ID_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO (ID_EVENTO);
ALTER TABLE BITACORADEASISTENCIA ADD CONSTRAINT FK_ID_MESAREDONDA FOREIGN KEY (ID_MESAREDONDA)REFERENCES MESAREDONDA (ID_MESAREDONDA);
ALTER TABLE BITACORADEASISTENCIA ADD CONSTRAINT FK_ID_REFRIGERIO FOREIGN KEY (ID_REFRIGERIO) REFERENCES REFRIGERIO (ID_REFRIGERIO);
ALTER TABLE MESAREDONDA ADD CONSTRAINT FK_ID_MODERADOR FOREIGN KEY (ID_MODERADOR) REFERENCES MODERADOR (ID_MODERADOR);
ALTER TABLE MESAREDONDA ADD CONSTRAINT FK_ID_EXPOSITOR FOREIGN KEY (ID_EXPOSITOR) REFERENCES EXPOSITOR (ID_EXPOSITOR);
ALTER TABLE MODERADOR ADD CONSTRAINT FK_PERSONA FOREIGN KEY (ID_PERSONA)REFERENCES PERSONA (ID_PERSONA);
ALTER TABLE EXPOSICION ADD CONSTRAINT FK_ID_TEMA FOREIGN KEY (ID_TEMA) REFERENCES TEMA (ID_TEMA);
ALTER TABLE EXPOSICION ADD CONSTRAINT FK_ID_EVENT FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO (ID_EVENTO);
ALTER TABLE EXPOSICION ADD CONSTRAINT FK_ID_EXPOSITOR2 FOREIGN KEY (ID_EXPOSITOR) REFERENCES EXPOSITOR (ID_EXPOSITOR);
ALTER TABLE EXPOSICION ADD CONSTRAINT FK_ID_SALA2 FOREIGN KEY (ID_SALA) REFERENCES SALAS (ID_SALA);
ALTER TABLE VISITANTES ADD CONSTRAINT FK_ID_PERSONA1 FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA);
ALTER TABLE EXPOSITOR ADD CONSTRAINT FK_ID_PERSONA2 FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA);
ALTER TABLE EXPOSITOR ADD CONSTRAINT FK_ID_CIUDAD FOREIGN KEY (ID_CIUDAD)REFERENCES CIUDAD (ID_CIUDAD);
ALTER TABLE EXPOSITOR ADD CONSTRAINT FK_ID_PAIS FOREIGN KEY (ID_PAIS) REFERENCES CIUDAD (ID_CIUDAD);
ALTER TABLE EXPOSITOR ADD CONSTRAINT FK_ID_CONTINENTE FOREIGN KEY (ID_CONTINENTE) REFERENCES  CONTINENTE (ID_CONTINENTE);
ALTER TABLE PERSONA ADD CONSTRAINT FK_IDTIPOSUSUARIO FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO);
