--CREACION DE TABLAS--

--CORREGIDA
CREATE TABLE SALAS(
       ID NUMBER,
       NOMBRE VARCHAR2(30),
       ESTADO VARCHAR2(1)
       CREATED_AT TIMESTAMP(3),
       UPDATED_AT TIMESTAMP(3)
);
--CORREGIDA
CREATE TABLE EVENTO(
       ID NUMBER,
       NOMBRE VARCHAR2(30),
       FECHA_INICIO TIMESTAMP(3),
       FECHA_FIN TIMESTAMP(3),
       SESION VARCHAR2(30),
       ESTADO VARCHAR2(1),
       CREATED_AT TIMESTAMP(3),
       UPDATED_AT TIMESTAMP(3)
);

CREATE TABLE INGREDIENTE (
       ID_INGREDIENTE NUMBER,
       INGREDIENTE VARCHAR2(30)
);

CREATE TABLE MENU(
       ID_MENU NUMBER,
       OPCION VARCHAR2(30),
       ID_INGREDIENTE NUMBER
);

CREATE TABLE REFRIGERIO(
       ID_REFRIGERIO NUMBER,
       DIA DATE,
       ID_MENU NUMBER
);


CREATE TABLE TEMA(
       ID_TEMA NUMBER,
       TEMA VARCHAR2(30),
       FECHA DATE,
       DURACION VARCHAR2(10)
);

CREATE TABLE EXPOSICION(
       ID_EXPOSICION NUMBER,
       ID_TEMA NUMBER,
       ID_EVENTO NUMBER,
       ID_EXPOSITOR NUMBER,
       ID_SALA NUMBER
);


CREATE TABLE EXPOSITOR(
       ID_EXPOSITOR NUMBER,
       ID_PERSONA NUMBER,
       ID_CIUDAD NUMBER,
       ID_PAIS NUMBER,
       ID_CONTINENTE NUMBER
);


CREATE TABLE CIUDAD(
       ID_CIUDAD NUMBER,
       CIUDAD VARCHAR2(30)
);

CREATE TABLE PAIS (
       ID_PAIS NUMBER,
       PAIS VARCHAR2(30)
);

CREATE TABLE CONTINENTE(
       ID_CONTINENTE NUMBER,
       CONTINENTE VARCHAR2(30)
);


CREATE TABLE MODERADOR(
       ID_MODERADOR NUMBER,
       ID_PERSONA NUMBER
);

CREATE TABLE MESAREDONDA(
       ID_MESAREDONDA NUMBER,
       ID_EXPOSITOR NUMBER,
       NOMBREMESA VARCHAR2(30),
       ID_MODERADOR NUMBER
);

CREATE TABLE BITACORADEASISTENCIA(
       ID_BITACORA NUMBER,
       ID_ASISTENTE NUMBER,
       ID_EVENTO NUMBER,
       ID_MESAREDONDA NUMBER,
       ID_PERSONA NUMBER,
       ID_REFRIGERIO NUMBER
);

CREATE TABLE VISITANTES(
       ID_VISITANTE NUMBER,
       ID_PERSONA NUMBER
);

--CORREGIDA
CREATE TABLE USERS(
       ID NUMBER,
       NAME VARCHAR2(30),
       EMAIL VARCHAR2(30),
       EMAIL_VERIFIED_AT TIMESTAMP(3),
       PASSWORD VARCHAR2(30),
       ESTADO VARCHAR2(1),
       REMEMBER_TOKEN VARCHAR2(255),
       CREATED_AT TIMESTAMP(3),
       UPDATED_AT TIMESTAMP(3)
);

CREATE TABLE TIPOUSUARIO(
       IDTIPOUSUARIO NUMBER,
       TIPO VARCHAR2(15)
);

--CORREGIDA
CREATE TABLE PERSONA(
       ID_PERSONA NUMBER,
       IDENTIFICACION VARCHAR2(10),
       NOMBRE VARCHAR2(30),
       APELLIDO VARCHAR2(30),
       SEXO VARCHAR2(1),
       ESTADOCIVIL VARCHAR2(1),
       DIRECCION VARCHAR2(30),
       ESTADO VARCHAR2(1),
       CREATED_AT TIMESTAMP(3),
       UPDATED_AT TIMESTAMP(3)

);

INSERT INTO TIPOUSUARIO VALUES(SECUENCIA_TIPOUSUARIO.NEXTVAL,'USUARIO');
INSERT INTO TIPOUSUARIO VALUES(SECUENCIA_TIPOUSUARIO.NEXTVAL,'VENDEDOR');
INSERT INTO TIPOUSUARIO VALUES(SECUENCIA_TIPOUSUARIO.NEXTVAL,'ADMINISTRADOR');

INSERT INTO PERSONA VALUES(SECUENCIA_PERSONA.NEXTVAL,'1315487493','RONALD','RUIZ','MASCULINO','CASADO','BAHIA','RONALD@GMAIL.COM','123',3);
COMMIT;
