--CREACION DE TABLAS--

--CORREGIDA
CREATE TABLE EVENTO(
       ID NUMBER,
       NOMBRE VARCHAR2(30),
       FECHA_INICIO TIMESTAMP(3),
       FECHA_FIN TIMESTAMP(3),
       SESION VARCHAR2(30),
       ESTADO VARCHAR2(1),
       CREATED_AT TIMESTAMP(3),
       UPDATED_AT TIMESTAMP(3)
);

CREATE TABLE INGREDIENTE (
       ID_INGREDIENTE NUMBER,
       INGREDIENTE VARCHAR2(30)
);

CREATE TABLE MENU(
       ID_MENU NUMBER,
       OPCION VARCHAR2(30),
       ID_INGREDIENTE NUMBER
);

CREATE TABLE REFRIGERIO(
       ID_REFRIGERIO NUMBER,
       DIA DATE,
       ID_MENU NUMBER
);


CREATE TABLE TEMA(
       ID_TEMA NUMBER,
       TEMA VARCHAR2(30),
       FECHA DATE,
       DURACION VARCHAR2(10)
);

CREATE TABLE EXPOSITOR(
       ID_EXPOSITOR NUMBER,
       ID_PERSONA NUMBER,
       ID_CIUDAD NUMBER,
       ID_PAIS NUMBER,
       ID_CONTINENTE NUMBER
);


CREATE TABLE CIUDAD(
       ID_CIUDAD NUMBER,
       CIUDAD VARCHAR2(30)
);

CREATE TABLE PAIS (
       ID_PAIS NUMBER,
       PAIS VARCHAR2(30)
);

CREATE TABLE CONTINENTE(
       ID_CONTINENTE NUMBER,
       CONTINENTE VARCHAR2(30)
);


CREATE TABLE MODERADOR(
       ID_MODERADOR NUMBER,
       ID_PERSONA NUMBER
);

CREATE TABLE MESAREDONDA(
       ID_MESAREDONDA NUMBER,
       ID_EXPOSITOR NUMBER,
       NOMBREMESA VARCHAR2(30),
       ID_MODERADOR NUMBER
);

CREATE TABLE BITACORADEASISTENCIA(
       ID_BITACORA NUMBER,
       ID_ASISTENTE NUMBER,
       ID_EVENTO NUMBER,
       ID_MESAREDONDA NUMBER,
       ID_PERSONA NUMBER,
       ID_REFRIGERIO NUMBER
);

CREATE TABLE VISITANTES(
       ID_VISITANTE NUMBER,
       ID_PERSONA NUMBER
);

CREATE TABLE TIPOUSUARIO(
       IDTIPOUSUARIO NUMBER,
       TIPO VARCHAR2(15)
);

--CORREGIDA
CREATE TABLE EXPOSICIONS(
       "ID" NUMBER(10)  NOT NULL,
       TITULO VARCHAR2(30) NOT NULL,
       DURACION VARCHAR2(20) NOT NULL,
       ESTADO VARCHAR2(1) NOT NULL,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

--CORREGIDA
CREATE TABLE PERMISSION_ROLE(
       "ID" NUMBER(10) NOT NULL,
       PERMISSION_ID NUMBER(10) NOT NULL,
       ROLE_ID NUMBER(10) NOT NULL,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

--CORREGIDA
CREATE TABLE PERMISSIONS(
       "ID" NUMBER(10) NOT NULL,
       "NAME" VARCHAR2(225) NOT NULL,
       SLUG VARCHAR2(225) NOT NULL,
       "DESCRIPTION" CLOB,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

--CORREGIDA
CREATE TABLE PERMISSION_USER(
       "ID" NUMBER(10) NOT NULL,
       PERMISSION_ID NUMBER(10) NOT NULL,
       USER_ID NUMBER(10) NOT NULL,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

--CORREGIDA
CREATE TABLE PERSONAS(
       "ID" NUMBER NOT NULL,
       IDENTIFICACION VARCHAR2(10) NOT NULL,
       NOMBRE VARCHAR2(30) NOT NULL,
       APELLIDO VARCHAR2(30) NOT NULL,
       SEXO VARCHAR2(1) NOT NULL,
       ESTADOCIVIL VARCHAR2(1) NOT NULL,
       DIRECCION VARCHAR2(30) NOT NULL,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

--CORREGIDA
CREATE TABLE "ROLES"(
       "ID" NUMBER(10) NOT NULL,
       "NAME" VARCHAR2(225)  NOT NULL,
       SLUG VARCHAR2(225)  NOT NULL,
       "DESCRIPTION" CLOB,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6),
       SPECIAL VARCHAR2(225)
);

--CORREGIDA
CREATE TABLE ROLE_USER(
       "ID" NUMBER(10) NOT NULL,
       ROLE_ID NUMBER(10) NOT NULL,
       USER_ID NUMBER(10) NOT NULL,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

--CORREGIDA
CREATE TABLE SALAS(
       "ID" NUMBER(10) NOT NULL,
       NOMBRE VARCHAR2(30) NOT NULL,
       ESTADO VARCHAR2(1) NOT NULL,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

--CORREGIDA
CREATE TABLE SESIONS(
       "ID" NUMBER(10) NOT NULL,
       NOMBRE VARCHAR2(50) NOT NULL,
       SALA_ID NUMBER(10),
       HORA_INICIO VARCHAR2(225) NOT NULL,
       HORA_FIN VARCHAR2(225) NOT NULL,
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6) 
);

--CORREGIDA
CREATE TABLE "USERS"(
       "ID" NUMBER(10) NOT NULL,
       "NAME" VARCHAR2(255) NOT NULL,
       EMAIL VARCHAR2(255) NOT NULL,
       EMAIL_VERIFIED_AT TIMESTAMP(6),
       "PASSWORD" VARCHAR2(255) NOT NULL,
       ESTADO VARCHAR2(1) NOT NULL,
       REMEMBER_TOKEN VARCHAR2(100),
       CREATED_AT TIMESTAMP(6),
       UPDATED_AT TIMESTAMP(6)
);

DROP TABLE EXPOSICIONS CASCADE CONSTRAINTS;
DROP TABLE PERMISSION_ROLE CASCADE CONSTRAINTS;
DROP TABLE PERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE PERMISSION_USER CASCADE CONSTRAINTS;
DROP TABLE PERSONAS CASCADE CONSTRAINTS;
DROP TABLE "ROLES" CASCADE CONSTRAINTS;
DROP TABLE ROLE_USER CASCADE CONSTRAINTS;
DROP TABLE SALAS CASCADE CONSTRAINTS;
DROP TABLE SESIONS CASCADE CONSTRAINTS;
DROP TABLE "USERS" CASCADE CONSTRAINTS;

